### ISSUE TITLE
Update site

### ISSUE THREAD

**Issue by fgregg** [datamade/data-collab-marketing#5]
We've gotten a number of new members, and we need to change the status of old members.

These logos need to be added as members. 

![tcr logo converted 1 1](https://user-images.githubusercontent.com/536941/52593426-92462080-2e0e-11e9-96e1-38786d1dabe4.png)

![mpc logo jpg not transparent](https://user-images.githubusercontent.com/536941/52593609-fec11f80-2e0e-11e9-820c-05f6830da7f1.jpg)
![mpc logo hi-res transparent](https://user-images.githubusercontent.com/536941/52593611-fff24c80-2e0e-11e9-8322-3efff093f33f.png)
[Bluhm Printable Logo.docx](https://github.com/datamade/data-collab-marketing/files/2853048/Bluhm.Printable.Logo.docx)

We need to add a section for "Founding members"
and move citytech and adler into that section

**Comment by derekeder** [comment]
Pinging this so I add it to my todo list in my email

**Comment by derekeder** [comment]
At check in this morning, we decided to hand this over to @jeancochrane as well as set up Netlify deployment & DNS for this site
